# Digital Egiz Backend Configuration

server:
  port: 8080
  readTimeout: 10
  writeTimeout: 10
  idleTimeout: 60

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: digital_egiz
  sslmode: disable

ditto:
  url: http://ditto:8080
  username: ditto
  password: ditto

kafka:
  brokers: kafka:9092
  consumerGroup: digital-egiz-backend
  topics:
    - ditto.twin.events.v1
    - ml.output.v1.anomaly
  securityEnable: false

jwt:
  expirationSec: 86400 # 24 hours

logging:
  level: info
  production: false 