# Digital EGIZ Backend Configuration

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60
  environment: "development"  # development, production, test

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "digital_egiz"
  sslmode: "disable"
  timezone: "UTC"

ditto:
  url: "http://ditto:8080"
  username: "ditto"
  password: "ditto"
  api_token: ""  # Optional API token for authorization

kafka:
  brokers: "kafka:9092"
  consumer_group: "digital-egiz"
  security_enable: false
  security_user: ""
  security_pass: ""

jwt:
  secret: "development-jwt-secret-key-change-in-production"
  expiration_hours: 24
  refresh_secret: "development-refresh-secret-key-change-in-production"
  refresh_expiration_hours: 168  # 7 days

log:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output_path: "stdout"  # stdout, stderr, or file path 